type Seed = [name: string, muscleGroup: string, equipment: string];

export const DEFAULT_EXERCISES: Seed[] = [
	['Bench Press', 'Chest', 'Barbell'],
	['Incline Bench Press', 'Chest', 'Barbell'],
	['Decline Bench Press', 'Chest', 'Barbell'],
	['Smith Machine Bench Press', 'Chest', 'Smith Machine'],
	['Smith Machine Incline Bench Press', 'Chest', 'Smith Machine'],
	['Smith Machine Decline Bench Press', 'Chest', 'Smith Machine'],
	['Incline Dumbbell Press', 'Chest', 'Dumbbell'],
	['Dumbbell Bench Press', 'Chest', 'Dumbbell'],
	['Chest Press', 'Chest', 'Machine'],
	['Pec Deck', 'Chest', 'Machine'],
	['Cable Fly', 'Chest', 'Cable'],
	['Low-to-High Cable Fly', 'Chest', 'Cable'],
	['Incline Cable Press', 'Chest', 'Cable'],
	['Decline Cable Press', 'Chest', 'Cable'],
	['Dips', 'Chest', 'Bodyweight'],
	['Push Up', 'Chest', 'Bodyweight'],
	['Deadlift', 'Back', 'Barbell'],
	['Smith Machine Deadlift', 'Back', 'Smith Machine'],
	['Barbell Row', 'Back', 'Barbell'],
	['Smith Machine Bent-Over Row', 'Back', 'Smith Machine'],
	['Pull Up', 'Back', 'Bodyweight'],
	['Chin Up', 'Back', 'Bodyweight'],
	['Lat Pulldown', 'Back', 'Cable'],
	['Single-Arm Lat Pulldown', 'Back', 'Cable'],
	['Seated Cable Row', 'Back', 'Cable'],
	['Seated Cable Row High Elbows', 'Back', 'Cable'],
	['Jammer Row', 'Back', 'Machine'],
	['Seated Cable Pullover', 'Back', 'Cable'],
	['Hanging Scapular Depressions', 'Back', 'Bodyweight'],
	['Kelso Shrug', 'Back', 'Dumbbell'],
	['Leaning Back Cable Shrug', 'Back', 'Cable'],
	['Straight-Arm Pulldown', 'Back', 'Cable'],
	['Single-Arm Dumbbell Row', 'Back', 'Dumbbell'],
	['Chest-Supported Row', 'Back', 'Machine'],
	['T-Bar Row', 'Back', 'Machine'],
	['Smith Machine Shrug', 'Back', 'Smith Machine'],
	['Overhead Press', 'Shoulders', 'Barbell'],
	['Smith Machine Overhead Press', 'Shoulders', 'Smith Machine'],
	['Smith Machine Behind-the-Neck Press', 'Shoulders', 'Smith Machine'],
	['Seated Dumbbell Press', 'Shoulders', 'Dumbbell'],
	['Shoulder Press', 'Shoulders', 'Machine'],
	['Lateral Raise', 'Shoulders', 'Dumbbell'],
	['Cable Lateral Raise', 'Shoulders', 'Cable'],
	['Leaning Cable Lateral Raise', 'Shoulders', 'Cable'],
	['Rear Delt Row', 'Shoulders', 'Cable'],
	['Reverse Fly', 'Shoulders', 'Dumbbell'],
	['Reverse Pec Deck', 'Shoulders', 'Machine'],
	['Face Pull', 'Shoulders', 'Cable'],
	['Smith Machine Upright Row', 'Shoulders', 'Smith Machine'],
	['Barbell Curl', 'Biceps', 'Barbell'],
	['Dumbbell Curl', 'Biceps', 'Dumbbell'],
	['Hammer Curl', 'Biceps', 'Dumbbell'],
	['Preacher Curl', 'Biceps', 'Machine'],
	['Cable Curl', 'Biceps', 'Cable'],
	['Bayesian Cable Curl', 'Biceps', 'Cable'],
	['Bayesian Hammer Cable Curl', 'Biceps', 'Cable'],
	['Spider Cable Curl', 'Biceps', 'Cable'],
	['Spider Hammer Cable Curl', 'Biceps', 'Cable'],
	['Triceps Pushdown', 'Triceps', 'Cable'],
	['Seated Incline Triceps Pushdown', 'Triceps', 'Cable'],
	['Overhead Cable Extension', 'Triceps', 'Cable'],
	['Katana Triceps Cable Extension', 'Triceps', 'Cable'],
	['Skull Crusher', 'Triceps', 'Barbell'],
	['JM Press', 'Triceps', 'Barbell'],
	['Close-Grip Bench Press', 'Triceps', 'Barbell'],
	['Smith Machine Close-Grip Bench Press', 'Triceps', 'Smith Machine'],
	['Back Squat', 'Legs', 'Barbell'],
	['Front Squat', 'Legs', 'Barbell'],
	['Smith Machine Squat', 'Legs', 'Smith Machine'],
	['Smith Machine Front Squat', 'Legs', 'Smith Machine'],
	['Smith Machine Split Squat', 'Legs', 'Smith Machine'],
	['Hack Squat', 'Legs', 'Machine'],
	['Leg Press', 'Legs', 'Machine'],
	['Leg Extension', 'Legs', 'Machine'],
	['Lying Leg Curl', 'Legs', 'Machine'],
	['Seated Leg Curl', 'Legs', 'Machine'],
	['Romanian Deadlift', 'Legs', 'Barbell'],
	['Smith Machine Romanian Deadlift', 'Legs', 'Smith Machine'],
	['Bulgarian Split Squat', 'Legs', 'Dumbbell'],
	['Walking Lunge', 'Legs', 'Dumbbell'],
	['Smith Machine Lunge', 'Legs', 'Smith Machine'],
	['Hip Thrust', 'Glutes', 'Barbell'],
	['Smith Machine Hip Thrust', 'Glutes', 'Smith Machine'],
	['Cable Kickback', 'Glutes', 'Cable'],
	['Hip Abduction', 'Glutes', 'Machine'],
	['Standing Calf Raise', 'Calves', 'Machine'],
	['Seated Calf Raise', 'Calves', 'Machine'],
	['Smith Machine Calf Raise', 'Calves', 'Smith Machine'],
	['Smith Machine Seated Calf Raise', 'Calves', 'Smith Machine'],
	['Cable Crunch', 'Core', 'Cable'],
	['Hanging Leg Raise', 'Core', 'Bodyweight'],
	['Plank', 'Core', 'Bodyweight']
];

export const MUSCLE_GROUPS = [
	'Chest',
	'Back',
	'Shoulders',
	'Biceps',
	'Triceps',
	'Legs',
	'Glutes',
	'Calves',
	'Core',
	'Full Body',
	'Other'
];

export const EQUIPMENT = [
	'Barbell',
	'Dumbbell',
	'Smith Machine',
	'Machine',
	'Cable',
	'Bodyweight',
	'Kettlebell',
	'Band',
	'Other'
];
